schema_version: 1

context:
  name: dashlab
  version: "0.3.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/dashlab-${{ version }}.tar.gz
  sha256: 2906b248c033a4dd4139338261b060992d7e5e7f6ae2af613da4cc023558437b

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=64
    - wheel
    - pip
  run:
    - python >=${{ python_min }}
    - anywidget
    - markdown

tests:
  - python:
      imports:
        - dashlab
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/asaboor-gh/dashlab
  summary: A Python package for dashboard and data visualization tools.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
